### ISSUE TITLE
Cycasp usage

### ISSUE THREAD

**Issue by Arkajyoti** [ghattab/cycasp#1]
Hi, 
Is there any comprehensive tutorial regarding this package? I recently learned trackpy and am learning bits of custom feature detection and image analysis. This package seems a good (non-machine learning) approach for single-cell bacterial detection. I have datasets that look like 
initial: 
![bac gif1](https://user-images.githubusercontent.com/30227887/66928767-37fefe80-f032-11e9-9b6e-f4a5a2982b93.gif)

final: 
![bac gif2](https://user-images.githubusercontent.com/30227887/66928821-45b48400-f032-11e9-8954-58f01198f240.gif)

The problem is isolating single features at a later stage and tracking. 

Thank you in advance

**Comment by ghattab** [comment]
Hi there! Thank you for the interest in this repo. 
Indeed, it relies on TrackPy. If you haven't yet taken a look at the associated [paper](https://www.frontiersin.org/articles/10.3389/fbioe.2018.00017/full) please do so. In short, the idea is to estimate the length and width of a cell, then complete other steps (e.g. tracking). This is species dependent but you can use the handy equation (1) under section 3.2.1. Particle Detection to estimate the particle size. In turn, this would create and track these particles (or features) in your time-lapse image data. This approach was used to tackle the task of subpopulation detection and not cell detection per say (so I favored 2+ particles per bacterial cell). Moreover, it circumvents the need for cell segmentation (individual cell delineation). However, in your case it's possible to define the particle to obtain 1 per cell.
Side note for tracking: the higher your temporal resolution the better the tracking, in this project we had 1 image each 30 min.

**Comment by ghattab** [comment]
Side note to the side note: The first GIF shows that you have spatial shift, you can consider registering the images before doing any feature extraction, then tracking. If you don't, you'll have to take into account in later steps the spatial shift (movement/drift in the x and y dimensions). The relevant question is: Do the bacteria intrinsically move in the medium/on the plate?
